### ISSUE TITLE
Error: require() of ES Module .../node_modules/p-queue/dist/index.js not supported

### ISSUE THREAD

**Issue by greghball** [plumelo/rollup-plugin-styler#3]
Using rollup-plugin-styler 1.6.0, Node 18 and Ubuntu 22.04 (with Rollup 4.9.1)

[!] Error: require() of ES Module .../node_modules/p-queue/dist/index.js from .../node_modules/rollup-plugin-styler/dist/index.cjs not supported.
Instead change the require of index.js in /home/gball/pw-main/pw/node_modules/rollup-plugin-styler/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.

**Comment by megheaiulian** [comment]
Thanks for adding this issue.
 I have not tested the CommonJS export but I will try to do that and fix the issue.
In a future version thou support for CommonJS must be dropped ...

**Comment by greghball** [comment]
Thanks!
